name: Linting

env:
  COMPOSER_VERSION: "2"
  COMPOSER_CACHE: "${{ github.workspace }}/.composer-cache"

on:
  push:
    branches:
      - develop
      - trunk
  pull_request:
    branches:
      - develop

jobs:
  phpcs:
    name: PHPCS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Set standard 10up cache directories
        run: |
          composer config -g cache-dir "${{ env.COMPOSER_CACHE }}"
      - name: Prepare composer cache
        uses: actions/cache@v2
        with:
          path: ${{ env.COMPOSER_CACHE }}
          key: composer-${{ env.COMPOSER_VERSION }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            composer-${{ env.COMPOSER_VERSION }}-
      - name: Set PHP version
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.2'
          coverage: none
          tools: composer:v2
      - name: composer install
        run: composer install --ignore-platform-reqs
      - name: PHPCS check
        with:
          phpcs_bin_path: './vendor/bin/phpcs . --runtime-set testVersion 5.6-'