name: Plugin asset/readme update
on:
  push:
    branches:
    - develop
jobs:
  master:
    name: Update plugin readme/tested up to
    runs-on: ubuntu-latest
    steps:
    - name: WordPress Plugin Readme/Assets Update
      uses: 10up/action-wordpress-plugin-asset-update@1.4.0
