name: PHP Compatibility

env:
  COMPOSER_VERSION: "2"
  COMPOSER_CACHE: "${{ github.workspace }}/.composer-cache"

on:
  push:
    branches:
      - develop
      - trunk
  pull_request:
    branches:
      - develop

jobs:
  php_compatibility:
    name: PHP minimum 5.6
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set standard 10up cache directories
        run: |
          composer config -g cache-dir "${{ env.COMPOSER_CACHE }}"

      - name: Prepare composer cache
        uses: actions/cache@v2
        with:
          path: ${{ env.COMPOSER_CACHE }}
          key: composer-${{ env.COMPOSER_VERSION }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            composer-${{ env.COMPOSER_VERSION }}-

      - name: Set PHP version
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.0'
          tools: composer:v2
          coverage: none

      - name: Install dependencies
        run: composer install

      - name: Check PHP Compatibility
        run: ./vendor/bin/phpcs -p simple-local-avatars.php includes --standard=PHPCompatibilityWP --extensions=php --runtime-set testVersion 5.6-