name: Plugin asset/readme update

on:
  push:
    branches:
      - trunk

jobs:
  trunk:
    name: Push to trunk
    runs-on: ubuntu-latest
    steps:
        uses: actions/checkout@v4
      - name: Install Composer dependencies
        run: composer install --no-dev
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
      - name: Build
        run: |
          npm install
          npm run build

      - name: WordPress.org plugin asset/readme update
        uses: 10up/action-wordpress-plugin-asset-update@stable
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
